"""Backend protocol and implementations for the scenario runner.

A Backend abstracts browser interaction so scenarios can run against either
a Playwright-launched browser (PlaywrightBackend) or an already-running
browser connected via CDP (CDPBackend).
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Backend(Protocol):
    """Protocol every scenario backend must implement."""

    def navigate(self, url: str) -> None: ...
    def reload(self) -> None: ...
    def click(self, target: dict, seed_id_map: dict) -> None: ...
    def dblclick(self, target: dict, seed_id_map: dict) -> None: ...
    def fill(self, target: dict, value: str, seed_id_map: dict) -> None: ...
    def select(self, target: dict, value: str, seed_id_map: dict) -> None: ...
    def press(self, target: dict, key: str, seed_id_map: dict) -> None: ...
    def wait_for_visible(self, target: dict, timeout: int, seed_id_map: dict) -> None: ...
    def wait_for_hidden(self, target: dict, timeout: int, seed_id_map: dict) -> None: ...
    def wait_for_text(self, text: str, timeout: int) -> None: ...
    def screenshot(self, path: str, full_page: bool = False) -> str: ...
    def wait_for_settled(self, timeout: int = 5000) -> None: ...
    def evaluate(self, js: str) -> Any: ...
    def get_text(self, target: dict, seed_id_map: dict) -> str: ...
    def close(self) -> None: ...
