"""Ticket operations — pure DB + business logic, no markdown sync or dashboard regen.

Extracted from tickets-cli.py so callers (CLI, serve.py, future API) can share
the same logic without side effects.  Every function here operates on an open
sqlite3.Connection and returns a result.  Callers are responsible for:

    1. Calling conn.commit() if they want to persist (functions do NOT commit).
    2. Running sync_to_markdown() / regenerate_dashboard() afterwards.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import sqlite3
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from constants import (
    DEFAULT_STATUS_BY_SECTION,
    SECTION_PREFIX,
    compute_status_on_move,
)

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def capture_commit_hash(project_path: str) -> str:
    """Return the short commit hash of HEAD for *project_path*, or '' on failure."""
    if not project_path:
        return ""
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%h"],
            cwd=project_path,
            capture_output=True,
            text=True,
            timeout=5,
        )
        return result.stdout.strip() if result.returncode == 0 else ""
    except Exception:
        return ""


# ---------------------------------------------------------------------------
# Typed errors — paired with an HTTP-status mapper in serve.py
# ---------------------------------------------------------------------------
# These subclass ValueError so legacy `except ValueError:` blocks keep working.
# New call sites should catch the specific type they care about, and route
# handlers can use DashboardHandler._send_typed_error() to emit a uniform
# {"code", "error"} body with the matching status code.


class AppError(ValueError):
    """Base class for application errors with an HTTP status mapping."""

    http_status: int = 500
    code: str = "internal_error"


class NotFoundError(AppError):
    http_status = 404
    code = "not_found"


class TicketNotFoundError(NotFoundError):
    code = "ticket_not_found"


class ProjectNotFoundError(NotFoundError):
    code = "project_not_found"


class ValidationError(AppError):
    http_status = 400
    code = "validation_error"


class ConflictError(AppError):
    http_status = 409
    code = "conflict"


def _find_ticket(
    conn: sqlite3.Connection, project_id: str, ticket_id: str
) -> sqlite3.Row:
    """Locate a ticket by ID (case-insensitive). Raises TicketNotFoundError if not found."""
    ticket = conn.execute(
        "SELECT * FROM tickets WHERE UPPER(id) = UPPER(?) AND project_id = ?",
        (ticket_id, project_id),
    ).fetchone()
    if not ticket:
        raise TicketNotFoundError(
            f"Ticket '{ticket_id}' not found in project '{project_id}'."
        )
    return ticket


# --- Summary one-liner ----------------------------------------------------
#
# A short status sentence cached on the ticket. Regenerated by the
# "Refresh ticket summary" system workflow when the content hash changes.
# The hash inputs are intentionally narrow: only fields that meaningfully
# affect the *meaning* of "where is this ticket up to" — title, description,
# acceptance criteria (text + checked state), section, status, and the
# status of any direct child tickets (so a parent's summary reacts to a
# child being closed). Tags / priority / sort order are deliberately
# excluded so re-prioritising or tagging doesn't churn the summary.


def compute_summary_hash(
    conn: sqlite3.Connection, project_id: str, ticket_id: str
) -> str:
    """Return a stable short hex hash of the ticket fields that drive the summary.

    Returns '' if the ticket is not found.
    """
    row = conn.execute(
        "SELECT id, title, description, section, status FROM tickets "
        "WHERE UPPER(id) = UPPER(?) AND project_id = ?",
        (ticket_id, project_id),
    ).fetchone()
    if not row:
        return ""

    criteria_rows = conn.execute(
        "SELECT text, checked FROM acceptance_criteria "
        "WHERE ticket_id = ? AND project_id = ? "
        "ORDER BY sort_order ASC, id ASC",
        (row["id"], project_id),
    ).fetchall()
    children_rows = conn.execute(
        "SELECT id, status FROM tickets "
        "WHERE parent = ? AND project_id = ? ORDER BY id ASC",
        (row["id"], project_id),
    ).fetchall()

    parts = [
        row["title"] or "",
        row["description"] or "",
        row["section"] or "",
        row["status"] or "",
        "|".join(f"{int(bool(c['checked']))}:{c['text'] or ''}" for c in criteria_rows),
        "|".join(f"{c['id']}:{c['status'] or ''}" for c in children_rows),
    ]
    blob = "\x1f".join(parts).encode("utf-8")
    return hashlib.sha256(blob).hexdigest()[:16]


def _next_sort_order(conn: sqlite3.Connection, project_id: str, section: str) -> int:
    """Return max(sort_order)+1 for *section*, or 0 if empty."""
    row = conn.execute(
        "SELECT COALESCE(MAX(sort_order), -1) + 1 AS next_order "
        "FROM tickets WHERE project_id = ? AND section = ?",
        (project_id, section),
    ).fetchone()
    return row["next_order"]


def auto_generate_id(conn: sqlite3.Connection, project_id: str, section: str) -> str:
    """Generate the next ticket ID for a section (e.g., B-14, BUG-10, I-03)."""
    prefix = SECTION_PREFIX.get(section, "B")
    sep = "-"
    pattern = f"{prefix}{sep}%"

    rows = conn.execute(
        "SELECT id FROM tickets WHERE project_id = ? AND id LIKE ?",
        (project_id, pattern),
    ).fetchall()

    max_num = 0
    for row in rows:
        tid = row["id"]
        suffix = tid[len(prefix) + len(sep) :]
        try:
            num = int(suffix)
            max_num = max(max_num, num)
        except ValueError:
            pass

    return f"{prefix}{sep}{max_num + 1:02d}"


# ---------------------------------------------------------------------------
# Kitchen — actor attribution, audit emission, eligibility, mode actions.
# See docs/KITCHEN.md §6-§9b. Activity events are written in the same DB
# transaction as the mutation that produced them; callers commit once.
# ---------------------------------------------------------------------------

CANONICAL_SECTIONS_FOR_ELIGIBILITY = ("Backlog", "WIP", "For Review")
CLEARED_DEP_STATUSES = ("done", "released")
ACTIVE_RUN_STATUSES = ("queued", "preparing", "running", "needs_input")


def utcnow_iso() -> str:
    """ISO-8601 UTC timestamp suitable for activity_events.occurred_at and similar."""
    return datetime.now(timezone.utc).isoformat()


@dataclass(frozen=True)
class ActorContext:
    """Who is performing a mutation. Threaded through every actions.py call.

    actor_type ∈ {'human', 'agent', 'system'}.
    actor_id is run_id (as str) for agent, user identifier for human, None for system.
    """

    actor_type: str
    actor_id: str | None = None

    @classmethod
    def human(cls, user_id: str | None = None) -> ActorContext:
        return cls(actor_type="human", actor_id=user_id)

    @classmethod
    def agent(cls, run_id: int | str) -> ActorContext:
        return cls(actor_type="agent", actor_id=str(run_id))

    @classmethod
    def system(cls) -> ActorContext:
        return cls(actor_type="system", actor_id=None)


def emit_event(
    conn: sqlite3.Connection,
    project_id: str,
    subject_type: str,
    subject_id: str,
    event_kind: str,
    payload: dict[str, Any],
    actor: ActorContext,
) -> int:
    """Insert one activity_events row in the caller's open transaction.

    Returns the new row id. Caller must commit. Mutation and emit_event MUST
    share a transaction so the audit log can never disagree with state.
    """
    cur = conn.execute(
        """
        INSERT INTO activity_events
            (project_id, subject_type, subject_id, actor_type, actor_id,
             event_kind, payload_json, occurred_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            project_id,
            subject_type,
            subject_id,
            actor.actor_type,
            actor.actor_id,
            event_kind,
            json.dumps(payload, ensure_ascii=False),
            utcnow_iso(),
        ),
    )
    return cur.lastrowid


# ---- Eligibility -----------------------------------------------------------


@dataclass(frozen=True)
class EligibilityResult:
    """Outcome of an eligibility check. Always carries reasons (for UI tooltips)."""

    eligible: bool
    reasons: tuple[str, ...]


def _has_active_run(
    conn: sqlite3.Connection, project_id: str, subject_type: str, subject_id: str
) -> bool:
    row = conn.execute(
        """
        SELECT 1 FROM runs
        WHERE project_id = ? AND subject_type = ? AND subject_id = ?
              AND status IN ('queued', 'preparing', 'running', 'needs_input')
        LIMIT 1
        """,
        (project_id, subject_type, subject_id),
    ).fetchone()
    return row is not None


def _automation_mode(
    conn: sqlite3.Connection, project_id: str, subject_type: str, subject_id: str
) -> str:
    """Return automation_mode for a subject; 'manual' if no row exists."""
    row = conn.execute(
        "SELECT automation_mode FROM automation_subjects "
        "WHERE project_id = ? AND subject_type = ? AND subject_id = ?",
        (project_id, subject_type, subject_id),
    ).fetchone()
    return row[0] if row else "manual"


def _deps_clear(
    conn: sqlite3.Connection, project_id: str, ticket_id: str
) -> tuple[bool, list[str]]:
    """Return (clear, blocking_reasons). See docs/KITCHEN.md §7 'Deps clear means'."""
    deps = conn.execute(
        "SELECT depends_on_id FROM depends WHERE ticket_id = ? AND project_id = ?",
        (ticket_id, project_id),
    ).fetchall()
    blocking: list[str] = []
    for (dep_id,) in deps:
        row = conn.execute(
            "SELECT id, section, status, archived FROM tickets "
            "WHERE UPPER(id) = UPPER(?) AND project_id = ?",
            (dep_id, project_id),
        ).fetchone()
        if not row:
            blocking.append(f"missing dep: {dep_id}")
            continue
        if row["archived"] == 1:
            blocking.append(f"dep {row['id']} is archived")
            continue
        if row["section"] != "Done" and row["status"] not in CLEARED_DEP_STATUSES:
            blocking.append(
                f"dep {row['id']} not done (section={row['section']}, status={row['status']})"
            )
    return (len(blocking) == 0, blocking)


def _journey_compiles_and_validates(
    conn: sqlite3.Connection, project_id: str, journey_id: str
) -> bool:
    """True if the journey can be compiled to a manifest and that manifest validates."""
    try:
        from journeys import compile_to_manifest
        from scenarios import validate_manifest
    except ImportError:
        return False
    try:
        manifest = compile_to_manifest(conn, project_id, journey_id)
        validate_manifest(manifest)
        return True
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Spec lifecycle (OpenSpec) — enforced here, in the shared core
# ---------------------------------------------------------------------------
#
# Both surfaces call into this module: `tickets-cli.py` for the headless agent
# path and `serve.py` for the dashboard. Putting the gates in a skill's prose or
# in dashboard JS would let the two diverge, so nothing below is duplicated
# outward — the skills and the HTTP handlers are thin callers.
#
# The lane (see constants.SPEC_LANES) changes how work is *described*. It never
# changes how work is *closed*: accept_ticket() runs the same verify + obligation
# + archive sequence in every lane, differing only in where the obligations are
# read from.

#: Sentinel used in the `spec` readiness flag when a lane-C ticket closes without
#: a spec delta because nothing observable changed. Must carry a reason.
NO_CHANGE_SENTINEL = "none"


def project_path_for(project_id: str) -> str:
    """Resolve a project's filesystem path from the registry, or '' if unknown."""
    try:
        from db import REGISTRY_PATH

        registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    except Exception:
        return ""
    for p in registry.get("projects", []):
        if p.get("id") == project_id:
            return os.path.expanduser(p.get("path", "") or "")
    return ""


def read_readiness_flag(
    conn: sqlite3.Connection, project_id: str, ticket_id: str, flag: str
) -> str:
    """Return a readiness flag's content, or '' when unset."""
    row = conn.execute(
        "SELECT content FROM readiness_flags WHERE ticket_id = ? AND project_id = ? AND flag = ?",
        (ticket_id, project_id, flag),
    ).fetchone()
    return (row["content"] or "") if row else ""


def write_readiness_flag(
    conn: sqlite3.Connection,
    project_id: str,
    ticket_id: str,
    flag: str,
    content: str,
    set_by: str = "cli",
) -> None:
    """Upsert a readiness flag. Caller commits."""
    conn.execute(
        """
        INSERT INTO readiness_flags (ticket_id, project_id, flag, content, set_by)
        VALUES (?, ?, ?, ?, ?)
        ON CONFLICT (ticket_id, project_id, flag)
        DO UPDATE SET content = excluded.content, set_by = excluded.set_by
        """,
        (ticket_id, project_id, flag, content, set_by),
    )


@dataclass(frozen=True)
class SpecLink:
    """Parsed `spec` readiness flag: which lane, and which OpenSpec change (if any).

    Wire format is one line so it survives the PRODUCT_BACKLOG.md round-trip:

        A:b-44-knowledge-ingestion-pipeline
        C:none - rename only, no observable behaviour change

    Lane C may name the sentinel instead of a change, but only with a reason:
    an unexplained "nothing changed" claim is exactly what the gate exists to
    stop being rubber-stamped.
    """

    lane: str = ""
    change: str = ""
    note: str = ""

    @property
    def declared(self) -> bool:
        return bool(self.lane)

    @property
    def claims_no_change(self) -> bool:
        return self.change == NO_CHANGE_SENTINEL

    def render(self) -> str:
        base = f"{self.lane}:{self.change or NO_CHANGE_SENTINEL}"
        return f"{base} - {self.note}" if self.note else base


def parse_spec_link(content: str) -> SpecLink:
    """Parse the `spec` readiness flag content. Unparseable input yields an empty link."""
    first = (content or "").strip().splitlines()[0] if (content or "").strip() else ""
    # Lane letter is case-insensitive: `--lane a` is a normal thing to type.
    m = re.match(r"^\s*([ABCabc])\s*:\s*([A-Za-z0-9._-]*)\s*(?:[-—]\s*(.*))?$", first)
    if not m:
        return SpecLink()
    return SpecLink(
        lane=m.group(1).upper(),
        change=(m.group(2) or "").strip(),
        note=(m.group(3) or "").strip(),
    )


def spec_link(conn: sqlite3.Connection, project_id: str, ticket_id: str) -> SpecLink:
    """The ticket's declared lane + change, from the `spec` readiness flag."""
    return parse_spec_link(read_readiness_flag(conn, project_id, ticket_id, "spec"))


@dataclass(frozen=True)
class VerifyRecord:
    """Parsed `verified` readiness flag — real evidence, not a checkbox."""

    command: str = ""
    exit_code: int = -1
    commit: str = ""
    ran_at: str = ""
    output_tail: str = ""

    @property
    def passed(self) -> bool:
        return self.exit_code == 0

    def render(self) -> str:
        head = f"exit={self.exit_code} commit={self.commit or '-'} at={self.ran_at} cmd={self.command}"
        if not self.output_tail:
            return head
        return head + "\n" + self.output_tail


def parse_verify_record(content: str) -> VerifyRecord:
    """Parse the `verified` readiness flag. Unparseable input yields exit_code -1."""
    text = (content or "").strip()
    if not text:
        return VerifyRecord()
    lines = text.splitlines()
    m = re.match(
        r"^exit=(-?\d+)\s+commit=(\S*)\s+at=(\S*)\s+cmd=(.*)$",
        lines[0].strip(),
    )
    if not m:
        return VerifyRecord()
    return VerifyRecord(
        exit_code=int(m.group(1)),
        commit="" if m.group(2) in ("", "-") else m.group(2),
        ran_at=m.group(3),
        command=m.group(4).strip(),
        output_tail="\n".join(lines[1:]),
    )


def verify_record(
    conn: sqlite3.Connection, project_id: str, ticket_id: str
) -> VerifyRecord:
    return parse_verify_record(
        read_readiness_flag(conn, project_id, ticket_id, "verified")
    )


# --- Verify command resolution --------------------------------------------
#
# Declared per project so step 1 of the close is deterministic rather than
# improvised by whichever agent happens to be running.

VERIFY_TIMEOUT_MS_DEFAULT = 600_000


def resolve_verify_command(project_path: str) -> tuple[str, int, str]:
    """Return (command, timeout_ms, source) for a project's verify step.

    Order: WORKFLOW.toml `[verify]`, then the conventional runners. `source` is
    'WORKFLOW.toml' when declared, otherwise the heuristic that matched, or ''
    when nothing was found — in which case the caller must ask once and write the
    answer into WORKFLOW.toml rather than guessing again next time.
    """
    root = Path(project_path)
    if not project_path or not root.is_dir():
        return ("", VERIFY_TIMEOUT_MS_DEFAULT, "")

    try:
        from workflow_config import load_workflow_config

        cfg = load_workflow_config(root).get("verify") or {}
        cmd = str(cfg.get("command", "") or "").strip()
        if cmd:
            timeout = int(cfg.get("timeout_ms", VERIFY_TIMEOUT_MS_DEFAULT))
            return (cmd, timeout, "WORKFLOW.toml")
    except Exception:
        pass  # a malformed WORKFLOW.toml must not silently disable the fallbacks

    if (root / "tests" / "run-tests.sh").is_file():
        return ("tests/run-tests.sh", VERIFY_TIMEOUT_MS_DEFAULT, "tests/run-tests.sh")

    pkg = root / "package.json"
    if pkg.is_file():
        try:
            scripts = json.loads(pkg.read_text(encoding="utf-8")).get("scripts") or {}
        except Exception:
            scripts = {}
        if scripts.get("test"):
            return ("npm test", VERIFY_TIMEOUT_MS_DEFAULT, "package.json test script")

    if (
        (root / "pytest.ini").is_file()
        or (root / "tests").is_dir()
        or (root / "pyproject.toml").is_file()
    ):
        return ("python3 -m pytest", VERIFY_TIMEOUT_MS_DEFAULT, "pytest")

    return ("", VERIFY_TIMEOUT_MS_DEFAULT, "")


VERIFY_OUTPUT_TAIL_LINES = 20


def run_verify(
    conn: sqlite3.Connection,
    project_id: str,
    ticket_id: str,
    project_path: str,
    actor: ActorContext | None = None,
) -> VerifyRecord:
    """Run the project's verify command and record the real result on the ticket.

    Records regardless of outcome — a failing verify is evidence too, and the
    accept gate reads exit_code rather than the flag's mere presence. Caller
    commits.
    """
    command, timeout_ms, source = resolve_verify_command(project_path)
    if not command:
        raise ValueError(
            f"No verify command for project {project_id!r}. Declare one in "
            f"{Path(project_path) / 'WORKFLOW.toml'}:\n\n"
            "    [verify]\n"
            '    command = "tests/run-tests.sh"\n'
        )

    started = datetime.now().isoformat(timespec="seconds")
    try:
        # stderr is merged into stdout rather than captured separately: the tail
        # is meant to show how the run actually ended, and concatenating two
        # separately-buffered streams puts all of stderr last, which routinely
        # buries the real summary line under warning noise.
        proc = subprocess.run(
            command,
            shell=True,
            cwd=project_path,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            timeout=max(1, timeout_ms) / 1000.0,
        )
        exit_code = proc.returncode
        combined = proc.stdout or ""
    except subprocess.TimeoutExpired:
        exit_code = 124
        combined = f"verify timed out after {timeout_ms}ms"

    tail_lines = [ln for ln in combined.strip().splitlines() if ln.strip()][
        -VERIFY_OUTPUT_TAIL_LINES:
    ]
    # 4-space indent so the tail survives the PRODUCT_BACKLOG.md round-trip as
    # continuation lines of the `Verified:` entry.
    tail = "\n".join(f"    {ln}" for ln in tail_lines)

    record = VerifyRecord(
        command=command,
        exit_code=exit_code,
        commit=capture_commit_hash(project_path),
        ran_at=started,
        output_tail=tail,
    )
    write_readiness_flag(
        conn,
        project_id,
        ticket_id,
        "verified",
        record.render(),
        set_by=f"verify:{source or 'fallback'}",
    )
    return record


# --- Gate predicates -------------------------------------------------------
#
# Each returns (passed, reasons). conditions.py exposes these to the workflow
# engine; accept_ticket() calls them directly. One implementation, two callers —
# the engine and the gate can never disagree.


def _spec_linked(
    conn: sqlite3.Connection, ticket: sqlite3.Row
) -> tuple[bool, list[str]]:
    """A lane has been declared: an OpenSpec change, or an explicit lane-C choice."""
    link = spec_link(conn, ticket["project_id"], ticket["id"])
    if not link.declared:
        return (
            False,
            [
                "no spec lane declared (run `tickets-cli.py spec <project> <id> --lane A|B|C`)"
            ],
        )
    if link.lane in ("A", "B") and (not link.change or link.claims_no_change):
        return (
            False,
            [
                f"lane {link.lane} requires an OpenSpec change name, got {link.change or '(empty)'!r}"
            ],
        )
    if link.claims_no_change and not link.note:
        return (False, ["lane C claims no spec delta but records no reason"])
    if link.change and not link.claims_no_change:
        return (True, [f"lane {link.lane}, change {link.change}"])
    return (True, [f"lane {link.lane}, no delta: {link.note}"])


def _spec_validates(
    conn: sqlite3.Connection, ticket: sqlite3.Row
) -> tuple[bool, list[str]]:
    """`openspec validate <change> --strict` exits 0 for the ticket's change.

    A lane-C ticket that legitimately has no delta passes vacuously — there is
    nothing to validate — but only because _spec_linked already forced the claim
    to be explicit and justified.
    """
    project_id = ticket["project_id"]
    link = spec_link(conn, project_id, ticket["id"])
    if not link.declared:
        return (False, ["no spec lane declared"])
    if link.claims_no_change:
        # Vacuously true — there is no delta to validate. Reported silently
        # because _spec_linked has already stated the claim and its reason;
        # saying it twice makes one decision look like two.
        return (True, [])
    if not link.change:
        return (False, [f"lane {link.lane} has no change name"])

    project_path = project_path_for(project_id)
    if not project_path:
        return (False, [f"project {project_id!r} has no path in the registry"])

    try:
        import openspec_adapter as osa
    except ImportError:
        return (False, ["openspec_adapter is not installed"])

    if not osa.is_initialised(project_path):
        return (
            False,
            [
                f"{project_path} has no openspec/ root (run `openspec init --tools claude`)"
            ],
        )

    # Already archived by a previous accept — the delta is canon now, so
    # re-validating the (moved) change directory would fail spuriously.
    if not osa.change_exists(project_path, link.change):
        if osa.archived_change_dirs(project_path, link.change):
            return (True, [f"change {link.change} is already archived"])
        return (False, [f"change {link.change} not found under openspec/changes/"])

    ok, reason = osa.check_cli(project_path)
    if not ok:
        return (False, [reason])

    res = osa.validate(project_path, link.change, strict=True)
    if res.ok:
        return (True, [f"openspec validate {link.change} --strict passed"])
    errors = osa.validation_errors(res) or [res.message]
    return (False, [f"openspec validate {link.change} --strict failed"] + errors)


def _verify_passed(
    conn: sqlite3.Connection, ticket: sqlite3.Row
) -> tuple[bool, list[str]]:
    """A `verified` flag exists, exited 0, and was recorded against current HEAD.

    The commit check is what stops a stale green from being reused: verify output
    from three commits ago is not evidence about the code being accepted.
    """
    project_id = ticket["project_id"]
    rec = verify_record(conn, project_id, ticket["id"])
    if not rec.command:
        return (
            False,
            ["no verify run recorded (run `tickets-cli.py verify <project> <id>`)"],
        )
    if not rec.passed:
        tail = rec.output_tail.strip().splitlines()
        detail = tail[-1].strip() if tail else ""
        return (
            False,
            [f"verify `{rec.command}` exited {rec.exit_code}"]
            + ([detail] if detail else []),
        )

    head = capture_commit_hash(project_path_for(project_id))
    if head and rec.commit and rec.commit != head:
        return (
            False,
            [
                f"verify passed at commit {rec.commit} but HEAD is {head} — re-run verify"
            ],
        )
    return (
        True,
        [f"verify `{rec.command}` passed at commit {rec.commit or 'unknown'}"],
    )


# --- The accept gate -------------------------------------------------------


@dataclass(frozen=True)
class AcceptGate:
    """Result of evaluating the close conditions for one ticket."""

    passed: bool
    failures: tuple[str, ...] = ()
    evidence: tuple[str, ...] = ()

    def refusal_message(self, project_id: str, ticket_id: str) -> str:
        """A specific, actionable refusal — never a bare 'not allowed'."""
        lines = [f"Cannot accept {ticket_id}: the close gate refused.", ""]
        lines += [f"  - {f}" for f in self.failures]
        lines += [
            "",
            "Fix the above, or override deliberately and on the record:",
            f'  tickets-cli.py accept {project_id} {ticket_id} --force "<reason>"',
        ]
        return "\n".join(lines)


def evaluate_accept_gate(conn: sqlite3.Connection, ticket: sqlite3.Row) -> AcceptGate:
    """Evaluate the uniform close conditions. Same in every lane.

    Step 1 of the close (running verify) is a separate, explicit action — this
    reads the recorded result rather than running commands as a side effect of
    an accept.
    """
    failures: list[str] = []
    evidence: list[str] = []

    ok, reasons = _verify_passed(conn, ticket)
    (evidence if ok else failures).extend(reasons)

    # spec_validates can only restate spec_linked's complaint when no lane is
    # declared — and it would shell out to `openspec` to do it. Short-circuit so
    # the refusal reads as one problem rather than two.
    linked_ok, reasons = _spec_linked(conn, ticket)
    (evidence if linked_ok else failures).extend(reasons)
    if linked_ok:
        ok, reasons = _spec_validates(conn, ticket)
        (evidence if ok else failures).extend(reasons)

    return AcceptGate(
        passed=not failures,
        failures=tuple(dict.fromkeys(failures)),
        evidence=tuple(dict.fromkeys(evidence)),
    )


def _forced_spec_flag_content(
    conn: sqlite3.Connection, project_id: str, ticket_id: str, reason: str
) -> str:
    """Preserve any declared lane while stamping the override reason onto it."""
    link = spec_link(conn, project_id, ticket_id)
    lane = link.lane or "C"
    change = link.change or NO_CHANGE_SENTINEL
    return SpecLink(
        lane=lane, change=change, note=f"accepted with --force: {reason}"
    ).render()


def _archive_change_for(
    conn: sqlite3.Connection, project_id: str, ticket_id: str, project_path: str
) -> str:
    """Archive the ticket's OpenSpec change, merging its delta into canon.

    Returns a one-line note for PRODUCT_SPECIFICATION.md, or '' when there was
    nothing to archive. Raises ValueError if the archive is attempted and fails —
    a half-closed ticket whose spec never reached canon is worse than a refusal.
    """
    link = spec_link(conn, project_id, ticket_id)
    if not link.change or link.claims_no_change:
        return ""

    try:
        import openspec_adapter as osa
    except ImportError:
        return ""

    if not osa.change_exists(project_path, link.change):
        archived = osa.archived_change_dirs(project_path, link.change)
        if archived:
            return f"Spec: `{link.change}` (already archived)"
        return ""

    res = osa.archive(project_path, link.change)
    if not res.ok:
        raise ValueError(
            f"Cannot accept {ticket_id}: `openspec archive {link.change}` failed "
            f"({res.message}). The spec delta must reach openspec/specs/ before "
            f"the ticket closes."
        )
    summary = osa.archive_summary(res)
    totals = summary.get("totals") or {}
    counts = (
        ", ".join(f"{n} {k}" for k, n in totals.items() if isinstance(n, int) and n)
        or "no requirement changes"
    )
    return f"Spec: `{link.change}` archived to openspec/specs/ ({counts})"


def _tests_covered(
    conn: sqlite3.Connection, ticket: sqlite3.Row
) -> tuple[bool, list[str]]:
    """Return (covered, reasons). Opt-in predicate for stricter user gates.

    Migration 15 collapsed the tests/smoke readiness flags into acceptance
    criteria, so the legacy "tests readiness flag has content" path is gone.
    Paths:
      1. A passing `verified` flag — a real verify run against current HEAD.
      2. A linked journey that compiles + validates.
      3. Explicit ticket.no_test_required = 1 with a non-empty rationale note.

    Path 1 exists because this predicate was a live trap: six projects already
    carry `tests_covered` in their `Backlog → WIP` triggers, while
    `journey_tickets` is empty and nothing sets `no_test_required`. Every one of
    those tickets was unsatisfiable — if the engine were switched on they could
    never advance. Accepting verify evidence gives the predicate a route that
    projects actually use.
    """
    reasons: list[str] = []
    project_id = ticket["project_id"]
    ticket_id = ticket["id"]

    # Path 1: a recorded verify run that passed against the current commit.
    ok, why = _verify_passed(conn, ticket)
    if ok:
        return (True, why)

    # Path 2: any linked journey that compiles + validates.
    journey_rows = conn.execute(
        "SELECT journey_id FROM journey_tickets WHERE ticket_id = ? AND project_id = ?",
        (ticket_id, project_id),
    ).fetchall()
    for (journey_id,) in journey_rows:
        if _journey_compiles_and_validates(conn, project_id, journey_id):
            return (True, [f"linked journey {journey_id} compiles+validates"])

    # Path 3: explicit no_test_required with non-empty note.
    if (
        ticket["no_test_required"] == 1
        and (ticket["no_test_required_note"] or "").strip()
    ):
        return (True, ["no_test_required (explicit)"])

    # No path satisfied — explain. Verify comes first because it is the route
    # most tickets should take.
    reasons.extend(why)
    if journey_rows and not any(
        _journey_compiles_and_validates(conn, project_id, jid)
        for (jid,) in journey_rows
    ):
        reasons.append("linked journeys do not compile/validate")
    elif not journey_rows:
        reasons.append("no linked journey")
    if ticket["no_test_required"] != 1:
        reasons.append("no_test_required not set")
    elif not (ticket["no_test_required_note"] or "").strip():
        reasons.append("no_test_required has no rationale note")
    return (False, reasons)


def _ticket_eligibility(
    conn: sqlite3.Connection, ticket: sqlite3.Row
) -> EligibilityResult:
    """Eligibility for a ticket subject. See docs/KITCHEN.md §7."""
    reasons: list[str] = []
    project_id = ticket["project_id"]
    ticket_id = ticket["id"]

    mode = _automation_mode(conn, project_id, "ticket", ticket_id)
    if mode != "auto":
        reasons.append(f"automation_mode is {mode}, not auto")

    if ticket["section"] not in CANONICAL_SECTIONS_FOR_ELIGIBILITY:
        reasons.append(f"section {ticket['section']!r} is not Backlog/WIP/For Review")

    if ticket["draft"] == 1:
        reasons.append("ticket is draft")
    if ticket["archived"] == 1:
        reasons.append("ticket is archived")

    if not (ticket["description"] or "").strip():
        reasons.append("description is empty")

    crit_count = conn.execute(
        "SELECT COUNT(*) FROM acceptance_criteria WHERE ticket_id = ? AND project_id = ?",
        (ticket_id, project_id),
    ).fetchone()[0]
    if crit_count == 0:
        reasons.append("no acceptance criteria")

    deps_ok, dep_reasons = _deps_clear(conn, project_id, ticket_id)
    if not deps_ok:
        reasons.extend(dep_reasons)

    if _has_active_run(conn, project_id, "ticket", ticket_id):
        reasons.append("active run already exists")

    # Binding: no agent dispatch without a declared spec lane. This is the
    # entry gate into automation — the Kitchen must not hand a ticket to an
    # implementing agent on free text alone. Safe to enforce even with old
    # tickets around, because eligibility already requires automation_mode
    # 'auto' (per-ticket opt-in, default manual): a ticket only meets this
    # gate once someone deliberately switches it on, and declaring a lane is
    # part of switching it on. The exit gate (verify + validate + archive)
    # stays at accept.
    spec_ok, spec_reasons = _spec_linked(conn, ticket)
    if not spec_ok:
        reasons.append(spec_reasons[0])

    eligible = (
        mode == "auto"
        and spec_ok
        and ticket["section"] in CANONICAL_SECTIONS_FOR_ELIGIBILITY
        and ticket["draft"] != 1
        and ticket["archived"] != 1
        and (ticket["description"] or "").strip()
        and crit_count > 0
        and deps_ok
        and not _has_active_run(conn, project_id, "ticket", ticket_id)
    )
    return EligibilityResult(eligible=bool(eligible), reasons=tuple(reasons))


def _journey_eligibility(
    conn: sqlite3.Connection, project_id: str, journey_id: str
) -> EligibilityResult:
    """Eligibility for a journey subject. See docs/KITCHEN.md §7."""
    reasons: list[str] = []
    mode = _automation_mode(conn, project_id, "journey", journey_id)
    if mode != "auto":
        reasons.append(f"automation_mode is {mode}, not auto")
    if not _journey_compiles_and_validates(conn, project_id, journey_id):
        reasons.append("manifest does not compile/validate")
    if _has_active_run(conn, project_id, "journey", journey_id):
        reasons.append("active run already exists")
    eligible = (
        mode == "auto"
        and _journey_compiles_and_validates(conn, project_id, journey_id)
        and not _has_active_run(conn, project_id, "journey", journey_id)
    )
    return EligibilityResult(eligible=bool(eligible), reasons=tuple(reasons))


def eligibility(
    conn: sqlite3.Connection, project_id: str, subject_type: str, subject_id: str
) -> EligibilityResult:
    """Compute Kitchen eligibility for any subject. See docs/KITCHEN.md §7.

    Always returns reasons, even when eligible=True (for UI tooltips).
    """
    if subject_type == "ticket":
        try:
            ticket = _find_ticket(conn, project_id, subject_id)
        except ValueError:
            return EligibilityResult(False, (f"ticket {subject_id!r} not found",))
        return _ticket_eligibility(conn, ticket)
    if subject_type == "journey":
        return _journey_eligibility(conn, project_id, subject_id)
    if subject_type == "investigation":
        return EligibilityResult(False, ("investigations not implemented in M1a",))
    return EligibilityResult(False, (f"unknown subject_type {subject_type!r}",))


# ---- Mode actions ----------------------------------------------------------


def _upsert_subject(
    conn: sqlite3.Connection,
    project_id: str,
    subject_type: str,
    subject_id: str,
    actor: ActorContext,
) -> None:
    """Lazy-create the automation_subjects row at default 'manual' if missing."""
    now = utcnow_iso()
    actor_str = (
        f"{actor.actor_type}:{actor.actor_id}" if actor.actor_id else actor.actor_type
    )
    conn.execute(
        """
        INSERT INTO automation_subjects
            (project_id, subject_type, subject_id, automation_mode,
             created_at, created_by, updated_at, updated_by)
        VALUES (?, ?, ?, 'manual', ?, ?, ?, ?)
        ON CONFLICT (project_id, subject_type, subject_id) DO NOTHING
        """,
        (project_id, subject_type, subject_id, now, actor_str, now, actor_str),
    )


def set_automation_mode(
    conn: sqlite3.Connection,
    project_id: str,
    subject_type: str,
    subject_id: str,
    mode: str,
    actor: ActorContext,
    pause_reason: str | None = None,
) -> None:
    """Set a subject's automation_mode. Emits the appropriate event(s).
    Caller must commit.

    Valid modes: 'manual', 'auto', 'paused'. `pause_reason` is optional —
    empty/whitespace strings are normalised to None. Lazy-creates the
    automation_subjects row if it doesn't exist.
    """
    if mode not in ("manual", "auto", "paused"):
        raise ValueError(f"invalid mode: {mode!r}")
    if mode == "paused":
        pause_reason = (pause_reason or "").strip() or None

    _upsert_subject(conn, project_id, subject_type, subject_id, actor)

    prior = conn.execute(
        "SELECT automation_mode, pause_reason FROM automation_subjects "
        "WHERE project_id = ? AND subject_type = ? AND subject_id = ?",
        (project_id, subject_type, subject_id),
    ).fetchone()
    prior_mode = prior["automation_mode"]
    prior_reason = prior["pause_reason"]

    if prior_mode == mode and (mode != "paused" or prior_reason == pause_reason):
        return  # no-op

    now = utcnow_iso()
    actor_str = (
        f"{actor.actor_type}:{actor.actor_id}" if actor.actor_id else actor.actor_type
    )
    conn.execute(
        """
        UPDATE automation_subjects
        SET automation_mode = ?, pause_reason = ?, updated_at = ?, updated_by = ?
        WHERE project_id = ? AND subject_type = ? AND subject_id = ?
        """,
        (
            mode,
            pause_reason if mode == "paused" else None,
            now,
            actor_str,
            project_id,
            subject_type,
            subject_id,
        ),
    )

    if mode == "paused":
        emit_event(
            conn,
            project_id,
            subject_type,
            subject_id,
            "pause_set",
            {"before": prior_mode, "after": "paused", "reason": pause_reason},
            actor,
        )
    elif prior_mode == "paused":
        emit_event(
            conn,
            project_id,
            subject_type,
            subject_id,
            "pause_cleared",
            {"before": "paused", "after": mode, "prior_reason": prior_reason},
            actor,
        )
    else:
        emit_event(
            conn,
            project_id,
            subject_type,
            subject_id,
            "mode_changed",
            {"before": prior_mode, "after": mode},
            actor,
        )


def set_no_test_required(
    conn: sqlite3.Connection,
    project_id: str,
    ticket_id: str,
    enabled: bool,
    note: str,
    actor: ActorContext,
) -> None:
    """Toggle the no_test_required eligibility bypass on a ticket.

    When enabled=True, note must be non-empty (the rationale).
    No event_kind in the M1a spine covers this — field_changed lands in M1b.
    Caller must commit.
    """
    if enabled and not (note or "").strip():
        raise ValueError("no_test_required requires a non-empty rationale note")

    ticket = _find_ticket(conn, project_id, ticket_id)
    flag = 1 if enabled else 0
    note_text = note.strip() if enabled else ""
    if (
        ticket["no_test_required"] == flag
        and (ticket["no_test_required_note"] or "") == note_text
    ):
        return  # no-op

    conn.execute(
        "UPDATE tickets SET no_test_required = ?, no_test_required_note = ?, updated_at = ? "
        "WHERE id = ? AND project_id = ?",
        (flag, note_text, utcnow_iso(), ticket["id"], project_id),
    )


# ---------------------------------------------------------------------------
# Core ticket operations
# ---------------------------------------------------------------------------


def move_ticket(
    conn: sqlite3.Connection,
    project_id: str,
    ticket_id: str,
    target_section: str,
    project_path: str = "",
    actor: ActorContext = ActorContext.human(),
) -> str:
    """Move a ticket to *target_section*.

    Uses compute_status_on_move() to decide the new status (preserves the
    current status when it is valid in the target section).  Captures the
    HEAD commit hash when moving to Done. Emits M1a spine events
    `section_change` and (when status changes) `status_change`.

    Returns the canonical ticket ID.
    """
    ticket = _find_ticket(conn, project_id, ticket_id)
    tid = ticket["id"]
    old_section = ticket["section"]
    old_status = ticket["status"]

    new_status = compute_status_on_move(old_status, target_section)
    sort_order = _next_sort_order(conn, project_id, target_section)

    # Capture commit hash when moving to Done
    commit_hash_val = ""
    if target_section == "Done":
        commit_hash_val = capture_commit_hash(project_path)

    now = datetime.now().isoformat()

    if commit_hash_val:
        conn.execute(
            "UPDATE tickets SET section = ?, status = ?, sort_order = ?, "
            "updated_at = ?, commit_hash = ? "
            "WHERE id = ? AND project_id = ?",
            (
                target_section,
                new_status,
                sort_order,
                now,
                commit_hash_val,
                tid,
                project_id,
            ),
        )
    else:
        conn.execute(
            "UPDATE tickets SET section = ?, status = ?, sort_order = ?, "
            "updated_at = ? "
            "WHERE id = ? AND project_id = ?",
            (target_section, new_status, sort_order, now, tid, project_id),
        )

    # M1a spine events — emit BEFORE side-effect hooks so they appear first in history.
    if old_section != target_section:
        emit_event(
            conn,
            project_id,
            "ticket",
            tid,
            "section_change",
            {"before": old_section, "after": target_section},
            actor,
        )
    if old_status != new_status:
        emit_event(
            conn,
            project_id,
            "ticket",
            tid,
            "status_change",
            {"before": old_status, "after": new_status},
            actor,
        )

    # Post-change hooks. Phase A migration (tidy-newt) moved parent-promote
    # and auto-accept into system workflows; what remains here is the journey
    # cascade and commit-hash capture in _after_section_change.
    _after_section_change(conn, project_id, tid, old_section, target_section)
    _after_status_change(conn, project_id, tid, old_status, new_status)

    return tid


def accept_ticket(
    conn: sqlite3.Connection,
    project_id: str,
    ticket_id: str,
    project_path: str,
    project_name: str,
    actor: ActorContext = ActorContext.human(),
    force: str = "",
) -> str:
    """Accept a ticket: move to Done with status 'done' and append to PRODUCT_SPECIFICATION.md.

    This is the gate. Before anything is written it requires:

      * `verify_passed`   — a real verify run that exited 0 against current HEAD
      * `spec_validates`  — `openspec validate <change> --strict` exits 0, or an
                            explicit-and-justified lane-C claim of no delta

    A failing check raises ValueError; both callers turn that into a non-zero
    exit / an HTTP error. The checks run identically whether this is reached from
    `tickets-cli.py accept` or from a dashboard click, because there is exactly
    one implementation.

    On success the change is archived — merging its delta into
    `openspec/specs/` — *before* PRODUCT_SPECIFICATION.md is written, so the
    archive diff lands in the same commit as the accept rather than stranding a
    second diff that needs its own PR.

    *force* is the escape hatch: a non-empty string skips the gate but records
    the reason on the ticket and in the audit log. Silent bypass is not offered.

    Emits M1a spine events `section_change` and `status_change` as needed.
    Returns the canonical ticket ID.
    """
    ticket = _find_ticket(conn, project_id, ticket_id)
    tid = ticket["id"]
    old_section = ticket["section"]
    old_status = ticket["status"]

    gate = evaluate_accept_gate(conn, ticket)
    if not gate.passed and not force:
        raise ValueError(gate.refusal_message(project_id, tid))

    archive_note = ""
    if force:
        emit_event(
            conn,
            project_id,
            "ticket",
            tid,
            "gate_override",
            {"reason": force, "blocked_by": list(gate.failures)},
            actor,
        )
        write_readiness_flag(
            conn,
            project_id,
            tid,
            "spec",
            _forced_spec_flag_content(conn, project_id, tid, force),
            set_by="accept:--force",
        )
    else:
        archive_note = _archive_change_for(conn, project_id, tid, project_path)

    commit_hash_val = capture_commit_hash(project_path)
    sort_order = _next_sort_order(conn, project_id, "Done")
    now = datetime.now().isoformat()

    conn.execute(
        "UPDATE tickets SET section = 'Done', status = 'done', "
        "sort_order = ?, updated_at = ?, commit_hash = ? "
        "WHERE id = ? AND project_id = ?",
        (sort_order, now, commit_hash_val, tid, project_id),
    )

    if old_section != "Done":
        emit_event(
            conn,
            project_id,
            "ticket",
            tid,
            "section_change",
            {"before": old_section, "after": "Done"},
            actor,
        )
    if old_status != "done":
        emit_event(
            conn,
            project_id,
            "ticket",
            tid,
            "status_change",
            {"before": old_status, "after": "done"},
            actor,
        )

    # Append to PRODUCT_SPECIFICATION.md
    spec_path = Path(project_path) / "PRODUCT_SPECIFICATION.md"
    today = datetime.now().strftime("%Y-%m-%d")
    entry = f"\n### {tid}: {ticket['title']}\n"
    entry += f"Priority: {ticket['priority']} | Status: released\n"
    commit_info = f" | Commit: {commit_hash_val}" if commit_hash_val else ""
    entry += f"Released: {today}{commit_info}\n"
    # Record what the gate actually saw, so the spec says how this was proven
    # rather than merely that someone pressed accept.
    rec = verify_record(conn, project_id, tid)
    if rec.command:
        entry += f"Verified: `{rec.command}` exit {rec.exit_code}\n"
    if archive_note:
        entry += f"{archive_note}\n"
    if force:
        entry += f"Gate overridden: {force}\n"
    if ticket["description"]:
        entry += f"{ticket['description']}\n"

    if spec_path.exists():
        content = spec_path.read_text(encoding="utf-8")
        # Insert before ## Archive if it exists, otherwise append
        if "## Archive" in content:
            content = content.replace("## Archive", entry + "\n## Archive")
        else:
            content = content.rstrip() + "\n" + entry
        spec_path.write_text(content, encoding="utf-8")
    else:
        spec_path.write_text(
            f"# Product Specification \u2014 {project_name}\n{entry}\n",
            encoding="utf-8",
        )

    # Post-change hooks
    _after_section_change(conn, project_id, tid, old_section, "Done")
    _after_status_change(conn, project_id, tid, old_status, "done")

    return tid


def add_ticket(
    conn: sqlite3.Connection,
    project_id: str,
    title: str,
    section: str = "Backlog",
    priority: str = "medium",
    description: str = "",
    parent: str | None = None,
    draft: bool = False,
    source_attachment_id: int | None = None,
    tags: list[str] | None = None,
    is_container: int = 0,
    actor: ActorContext = ActorContext.human(),
    emit_created_event: bool = True,
) -> str:
    """Add a new ticket.  Auto-generates the ID from *section* prefix.

    Returns the new ticket ID.

    Callers that want to emit a richer ticket_created event themselves (e.g.
    seek attaches scan source-line metadata; seed_project tags origin=seed)
    should pass emit_created_event=False and call emit_event directly.
    """
    status = DEFAULT_STATUS_BY_SECTION[section]
    ticket_id = auto_generate_id(conn, project_id, section)
    sort_order = _next_sort_order(conn, project_id, section)

    conn.execute(
        "INSERT INTO tickets (id, project_id, title, priority, status, "
        "section, description, parent, sort_order, draft, source_attachment_id, is_container) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (
            ticket_id,
            project_id,
            title,
            priority,
            status,
            section,
            description,
            parent,
            sort_order,
            int(draft),
            source_attachment_id,
            1 if is_container else 0,
        ),
    )

    if tags:
        for tag in tags:
            tag = tag.strip().lower()
            if tag:
                conn.execute(
                    "INSERT OR IGNORE INTO ticket_tags (ticket_id, project_id, tag) "
                    "VALUES (?, ?, ?)",
                    (ticket_id, project_id, tag),
                )

    if emit_created_event:
        # Default origin: 'human' for direct UI/CLI creation, 'agent' when an
        # agent-actor calls in (e.g. workflow run that spawns a sub-ticket).
        origin = "agent" if actor.actor_type == "agent" else "human"
        emit_event(
            conn,
            project_id,
            "ticket",
            ticket_id,
            "ticket_created",
            {
                "id": ticket_id,
                "title": title,
                "section": section,
                "origin": origin,
                "draft": bool(draft),
            },
            actor,
        )

    return ticket_id


def update_ticket(
    conn: sqlite3.Connection,
    project_id: str,
    ticket_id: str,
    *,
    title: str | None = None,
    priority: str | None = None,
    status: str | None = None,
    description: str | None = None,
    parent: str | None = ...,  # sentinel — None means "clear parent"
    summary: str | None = None,
    add_criteria: list[str] | None = None,
    check_criteria: int | None = None,
    uncheck_criteria: int | None = None,
    remove_criteria: int | None = None,
    add_depends: list[str] | None = None,
    remove_depends: list[str] | None = None,
    add_tags: list[str] | None = None,
    remove_tags: list[str] | None = None,
    add_branches: list[str] | None = None,
    remove_branches: list[str] | None = None,
    is_container: int | None = None,
    actor: ActorContext = ActorContext.human(),
) -> str:
    """Partial update of a ticket.  Only fields that are not None/sentinel are changed.

    Emits M1a spine `status_change` and `criteria_check` events. Other field
    edits (title, description, criteria text, deps) emit no event in M1a — they
    move to M1b's `field_changed` / `criteria_added` / `criteria_removed` /
    `criteria_changed` / `dependency_changed` vocabulary.

    Returns the canonical ticket ID.
    """
    ticket = _find_ticket(conn, project_id, ticket_id)
    tid = ticket["id"]
    old_status = ticket["status"]

    # ---- scalar field updates ----
    updates: dict[str, object] = {}
    if title is not None:
        updates["title"] = title
    if priority is not None:
        updates["priority"] = priority.lower()
    if status is not None:
        updates["status"] = status.lower()
    if description is not None:
        updates["description"] = description
    if parent is not ...:
        # None clears the parent; a string sets it
        updates["parent"] = parent if parent else None
    if summary is not None:
        updates["summary"] = summary
    if is_container is not None:
        updates["is_container"] = 1 if is_container else 0

    if updates:
        updates["updated_at"] = datetime.now().isoformat()
        set_clause = ", ".join(f"{k} = ?" for k in updates)
        values = list(updates.values()) + [tid, project_id]
        conn.execute(
            f"UPDATE tickets SET {set_clause} WHERE id = ? AND project_id = ?",
            values,
        )

    # ---- acceptance criteria operations ----
    if add_criteria:
        for text in add_criteria:
            row = conn.execute(
                "SELECT COALESCE(MAX(sort_order), -1) + 1 AS next "
                "FROM acceptance_criteria WHERE ticket_id = ? AND project_id = ?",
                (tid, project_id),
            ).fetchone()
            conn.execute(
                "INSERT INTO acceptance_criteria "
                "(ticket_id, project_id, text, checked, sort_order) VALUES (?, ?, ?, 0, ?)",
                (tid, project_id, text, row["next"]),
            )

    if check_criteria is not None:
        _update_criterion(conn, tid, project_id, check_criteria, checked=1, actor=actor)

    if uncheck_criteria is not None:
        _update_criterion(
            conn, tid, project_id, uncheck_criteria, checked=0, actor=actor
        )

    if remove_criteria is not None:
        _remove_criterion(conn, tid, project_id, remove_criteria)

    # ---- depends operations ----
    if add_depends:
        for dep in add_depends:
            conn.execute(
                "INSERT OR IGNORE INTO depends (ticket_id, project_id, depends_on_id) "
                "VALUES (?, ?, ?)",
                (tid, project_id, dep),
            )

    if remove_depends:
        for dep in remove_depends:
            conn.execute(
                "DELETE FROM depends "
                "WHERE ticket_id = ? AND project_id = ? AND depends_on_id = ?",
                (tid, project_id, dep),
            )

    # ---- tag operations ----
    if add_tags:
        for tag in add_tags:
            tag = tag.strip().lower()
            if tag:
                conn.execute(
                    "INSERT OR IGNORE INTO ticket_tags (ticket_id, project_id, tag) "
                    "VALUES (?, ?, ?)",
                    (tid, project_id, tag),
                )

    if remove_tags:
        for tag in remove_tags:
            tag = tag.strip().lower()
            if tag:
                conn.execute(
                    "DELETE FROM ticket_tags "
                    "WHERE ticket_id = ? AND project_id = ? AND tag = ?",
                    (tid, project_id, tag),
                )

    # ---- branch operations ----
    if add_branches:
        for branch in add_branches:
            branch = branch.strip()
            if branch:
                conn.execute(
                    "INSERT OR IGNORE INTO ticket_branches "
                    "(ticket_id, project_id, branch_name) VALUES (?, ?, ?)",
                    (tid, project_id, branch),
                )

    if remove_branches:
        for branch in remove_branches:
            branch = branch.strip()
            if branch:
                conn.execute(
                    "DELETE FROM ticket_branches "
                    "WHERE ticket_id = ? AND project_id = ? AND branch_name = ?",
                    (tid, project_id, branch),
                )

    # M1a spine event for status change. Field/dep/criteria-text events land in M1b.
    # Other field edits (title, description, criteria text, deps) emit no event in
    # M1a — they move to M1b's `field_changed` / `criteria_added` / `criteria_removed`
    # / `criteria_changed` / `dependency_changed` vocabulary.
    new_status = updates.get("status", old_status)
    if new_status != old_status:
        emit_event(
            conn,
            project_id,
            "ticket",
            tid,
            "status_change",
            {"before": old_status, "after": new_status},
            actor,
        )
        _after_status_change(conn, project_id, tid, old_status, new_status)

    return tid


def confirm_ticket(conn: sqlite3.Connection, project_id: str, ticket_id: str) -> str:
    """Confirm a draft ticket — sets draft=0 and clears source_attachment_id."""
    ticket = _find_ticket(conn, project_id, ticket_id)
    tid = ticket["id"]
    conn.execute(
        "UPDATE tickets SET draft = 0, source_attachment_id = NULL, updated_at = ? "
        "WHERE id = ? AND project_id = ?",
        (datetime.now().isoformat(), tid, project_id),
    )
    return tid


# ---------------------------------------------------------------------------
# Criteria helpers (internal)
# ---------------------------------------------------------------------------


def _update_criterion(
    conn: sqlite3.Connection,
    tid: str,
    project_id: str,
    index: int,
    checked: int,
    actor: ActorContext = ActorContext.human(),
):
    """Update the checked state of the Nth criterion (1-indexed). Emits `criteria_check`."""
    criteria = conn.execute(
        "SELECT id, checked FROM acceptance_criteria "
        "WHERE ticket_id = ? AND project_id = ? ORDER BY sort_order ASC",
        (tid, project_id),
    ).fetchall()
    if 1 <= index <= len(criteria):
        criterion = criteria[index - 1]
        before = bool(criterion["checked"])
        after = bool(checked)
        if before == after:
            return  # no-op
        conn.execute(
            "UPDATE acceptance_criteria SET checked = ? WHERE id = ?",
            (checked, criterion["id"]),
        )
        emit_event(
            conn,
            project_id,
            "ticket",
            tid,
            "criteria_check",
            {"criterion_id": criterion["id"], "before": before, "after": after},
            actor,
        )
    else:
        raise IndexError(f"Criterion index {index} out of range (1-{len(criteria)})")


def _remove_criterion(conn: sqlite3.Connection, tid: str, project_id: str, index: int):
    """Remove the Nth criterion (1-indexed)."""
    criteria = conn.execute(
        "SELECT id FROM acceptance_criteria "
        "WHERE ticket_id = ? AND project_id = ? ORDER BY sort_order ASC",
        (tid, project_id),
    ).fetchall()
    if 1 <= index <= len(criteria):
        conn.execute(
            "DELETE FROM acceptance_criteria WHERE id = ?",
            (criteria[index - 1]["id"],),
        )
    else:
        raise IndexError(f"Criterion index {index} out of range (1-{len(criteria)})")


# ---------------------------------------------------------------------------
# Post-change hooks
# ---------------------------------------------------------------------------


def _has_open_bugs(conn: sqlite3.Connection, project_id: str, ticket_id: str) -> bool:
    """Return True if *ticket_id* has any child bugs not in a terminal status."""
    terminal = {"done", "for-review", "bug-fixed"}
    children = conn.execute(
        "SELECT status FROM tickets WHERE parent = ? AND project_id = ?",
        (ticket_id, project_id),
    ).fetchall()
    return any(c["status"] not in terminal for c in children)


def _after_status_change(
    conn: sqlite3.Connection,
    project_id: str,
    ticket_id: str,
    old_status: str,
    new_status: str,
) -> None:
    """Run post-status-change side effects.

    Phase A migration (tidy-newt): the parent-promote rule was migrated to a
    system workflow ("Parent auto-promote", workflows_seed.py) — the
    dispatcher's next tick picks up parents whose children all reached
    terminal status and applies the move via the workflow engine.
    """
    return


def _after_section_change(
    conn: sqlite3.Connection,
    project_id: str,
    ticket_id: str,
    old_section: str,
    new_section: str,
) -> None:
    """Run post-move logic after a ticket changes section.

    Phase A migration (tidy-newt): parent-promote moved to a system workflow.
    This hook now only handles the journey cascade and commit-hash capture
    (both of which are write side effects this transaction owns).
    """
    # Kitchen M4: when a ticket reaches Done, cascade to any linked journeys.
    # Each linked journey gets a scenario run queued with triggered_by='journey-cascade'.
    # If the journey already has an active run, the partial unique index simply
    # rejects the second claim — that's fine.
    if new_section == "Done" and old_section != "Done":
        _cascade_to_linked_journeys(conn, project_id, ticket_id)

    # Capture commit hash when moving to Done (if not already set)
    if new_section == "Done":
        ticket = conn.execute(
            "SELECT commit_hash FROM tickets WHERE id = ? AND project_id = ?",
            (ticket_id, project_id),
        ).fetchone()
        if ticket and not ticket["commit_hash"]:
            # Try to find project path from registry for commit hash capture
            try:
                import json as _json

                from db import REGISTRY_PATH

                registry = _json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
                for p in registry.get("projects", []):
                    if p["id"] == project_id:
                        project_path = os.path.expanduser(p.get("path", ""))
                        commit_hash_val = capture_commit_hash(project_path)
                        if commit_hash_val:
                            conn.execute(
                                "UPDATE tickets SET commit_hash = ? WHERE id = ? AND project_id = ?",
                                (commit_hash_val, ticket_id, project_id),
                            )
                        break
            except Exception:
                pass  # Best-effort — move_ticket already captures this in most paths


def _cascade_to_linked_journeys(
    conn: sqlite3.Connection,
    project_id: str,
    ticket_id: str,
) -> None:
    """Queue a scenario run for every journey linked to *ticket_id*.

    Best-effort: if kitchen isn't available (e.g. tests not exercising it,
    or the project has no resolvable path), we log and move on. The journey
    table may also not exist in pre-migration DBs.
    """
    try:
        rows = conn.execute(
            "SELECT DISTINCT journey_id FROM journey_tickets "
            "WHERE ticket_id = ? AND project_id = ?",
            (ticket_id, project_id),
        ).fetchall()
    except sqlite3.OperationalError:
        return  # journey_tickets table doesn't exist
    if not rows:
        return

    # Lazy import to break the actions ↔ kitchen ↔ runners cycle.
    try:
        import kitchen as _kitchen
        from db import get_db
    except ImportError:
        return

    for r in rows:
        jid = r["journey_id"] if "journey_id" in r.keys() else r[0]
        # Each cascade run is a separate trigger_run call so a partial unique
        # index conflict on one journey doesn't block others. trigger_run
        # opens its own connection — passes get_db so it can.
        try:
            _kitchen.trigger_run(
                get_db,
                project_id,
                "journey",
                jid,
                {},
                triggered_by="journey-cascade",
            )
        except Exception:
            pass  # don't break the section move on a cascade failure


# ---------------------------------------------------------------------------
# Branch operations
# ---------------------------------------------------------------------------


def link_branch(
    conn: sqlite3.Connection,
    project_id: str,
    ticket_id: str,
    branch_name: str,
    remote: str = "origin",
    auto_linked: bool = False,
) -> bool:
    """Link a branch to a ticket.  Returns True if a new link was created."""
    _find_ticket(conn, project_id, ticket_id)  # validate ticket exists
    cur = conn.execute(
        "INSERT OR IGNORE INTO ticket_branches "
        "(ticket_id, project_id, branch_name, remote, auto_linked) "
        "VALUES (?, ?, ?, ?, ?)",
        (ticket_id, project_id, branch_name, remote, int(auto_linked)),
    )
    return cur.rowcount > 0


def unlink_branch(
    conn: sqlite3.Connection,
    project_id: str,
    ticket_id: str,
    branch_name: str,
) -> bool:
    """Unlink a branch from a ticket.  Returns True if a link was removed."""
    cur = conn.execute(
        "DELETE FROM ticket_branches "
        "WHERE ticket_id = ? AND project_id = ? AND branch_name = ?",
        (ticket_id, project_id, branch_name),
    )
    return cur.rowcount > 0


def get_ticket_branches(
    conn: sqlite3.Connection,
    project_id: str,
    ticket_id: str,
) -> list[dict]:
    """Return all branches linked to a ticket."""
    rows = conn.execute(
        "SELECT * FROM ticket_branches "
        "WHERE ticket_id = ? AND project_id = ? ORDER BY created_at",
        (ticket_id, project_id),
    ).fetchall()
    return [dict(r) for r in rows]


def get_project_branches(
    conn: sqlite3.Connection,
    project_id: str,
) -> list[dict]:
    """Return all branch links for a project."""
    rows = conn.execute(
        "SELECT * FROM ticket_branches WHERE project_id = ? ORDER BY ticket_id, created_at",
        (project_id,),
    ).fetchall()
    return [dict(r) for r in rows]


def _match_branch_to_ticket(branch_name: str, ticket_ids: list[str]) -> str | None:
    """Check if branch_name starts with a ticket ID (case-insensitive).

    Handles both direct names (B-01-feature) and path prefixes (feature/B-01-thing).
    Returns the matched ticket ID or None.
    """
    # Strip remote prefix if present
    if "/" in branch_name:
        parts = branch_name.split("/")
        # origin/B-01-feature → B-01-feature
        # origin/feature/B-01-thing → feature/B-01-thing → B-01-thing
        candidates = ["/".join(parts[i:]) for i in range(len(parts))]
    else:
        candidates = [branch_name]

    lower_name_candidates = [c.lower() for c in candidates]

    # Sort ticket IDs longest-first to match BUG-03 before B-0
    for tid in sorted(ticket_ids, key=len, reverse=True):
        tid_lower = tid.lower()
        for cand in lower_name_candidates:
            # Must start with ticket ID followed by end-of-string, dash, or slash
            if (
                cand == tid_lower
                or cand.startswith(tid_lower + "-")
                or cand.startswith(tid_lower + "/")
            ):
                return tid
    return None


def scan_branches(
    conn: sqlite3.Connection,
    project_id: str,
    project_path: str,
) -> dict:
    """Scan remote branches and auto-link those matching ticket IDs.

    Returns {"linked": N, "total_remote": N} or {"error": str}.
    """
    if not project_path:
        return {"error": "no project path", "linked": 0, "total_remote": 0}

    # Get remote branch names
    try:
        result = subprocess.run(
            ["git", "branch", "-r", "--list", "origin/*"],
            cwd=project_path,
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode != 0:
            return {"error": "git branch failed", "linked": 0, "total_remote": 0}
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return {"error": "git not available", "linked": 0, "total_remote": 0}

    branches = []
    for line in result.stdout.strip().splitlines():
        name = line.strip()
        if " -> " in name:
            continue  # skip HEAD pointers like origin/HEAD -> origin/main
        if name:
            branches.append(name)

    # Load all ticket IDs for this project
    ticket_rows = conn.execute(
        "SELECT id FROM tickets WHERE project_id = ?", (project_id,)
    ).fetchall()
    ticket_ids = [r["id"] for r in ticket_rows]

    linked = 0
    for branch in branches:
        # Strip "origin/" for matching but store the short name
        short_name = (
            branch.replace("origin/", "", 1) if branch.startswith("origin/") else branch
        )
        matched_tid = _match_branch_to_ticket(short_name, ticket_ids)
        if matched_tid:
            cur = conn.execute(
                "INSERT OR IGNORE INTO ticket_branches "
                "(ticket_id, project_id, branch_name, remote, auto_linked) "
                "VALUES (?, ?, ?, 'origin', 1)",
                (matched_tid, project_id, short_name),
            )
            if cur.rowcount > 0:
                linked += 1

    # Update ahead/behind for all linked branches
    all_linked = conn.execute(
        "SELECT ticket_id, branch_name FROM ticket_branches WHERE project_id = ?",
        (project_id,),
    ).fetchall()

    for row in all_linked:
        try:
            res = subprocess.run(
                [
                    "git",
                    "rev-list",
                    "--count",
                    "--left-right",
                    f"origin/main...origin/{row['branch_name']}",
                ],
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=5,
            )
            if res.returncode == 0 and "\t" in res.stdout.strip():
                behind_str, ahead_str = res.stdout.strip().split("\t")
                conn.execute(
                    "UPDATE ticket_branches SET ahead = ?, behind = ?, last_synced = ? "
                    "WHERE ticket_id = ? AND project_id = ? AND branch_name = ?",
                    (
                        int(ahead_str),
                        int(behind_str),
                        datetime.now().isoformat(),
                        row["ticket_id"],
                        project_id,
                        row["branch_name"],
                    ),
                )
        except (FileNotFoundError, subprocess.TimeoutExpired, OSError, ValueError):
            pass  # best-effort

    return {"linked": linked, "total_remote": len(branches)}


def scan_prs(
    conn: sqlite3.Connection,
    project_id: str,
    project_path: str,
) -> dict:
    """Enrich branch links with PR metadata via `gh pr list`.

    Returns {"updated": N} or {"error": str}.
    """
    if not project_path:
        return {"error": "no project path", "updated": 0}

    try:
        result = subprocess.run(
            [
                "gh",
                "pr",
                "list",
                "--json",
                "number,title,headRefName,state,url,isDraft",
                "--limit",
                "100",
                "--state",
                "all",
            ],
            cwd=project_path,
            capture_output=True,
            text=True,
            timeout=15,
        )
        if result.returncode != 0:
            return {"error": "gh pr list failed", "updated": 0}
        prs = json.loads(result.stdout)
    except (
        FileNotFoundError,
        subprocess.TimeoutExpired,
        json.JSONDecodeError,
        OSError,
        ValueError,
    ):
        return {"error": "gh not available", "updated": 0}

    # Load ticket IDs for auto-linking unlinked PR branches
    ticket_rows = conn.execute(
        "SELECT id FROM tickets WHERE project_id = ?", (project_id,)
    ).fetchall()
    ticket_ids = [r["id"] for r in ticket_rows]

    updated = 0
    for pr in prs:
        head_ref = pr.get("headRefName", "")
        if not head_ref:
            continue

        pr_number = pr.get("number")
        pr_url = pr.get("url", "")
        state = pr.get("state", "").upper()
        is_draft = pr.get("isDraft", False)

        if state == "MERGED":
            pr_status = "merged"
        elif state == "CLOSED":
            pr_status = "closed"
        elif is_draft:
            pr_status = "draft"
        else:
            pr_status = "open"

        # Try to update existing branch link
        cur = conn.execute(
            "UPDATE ticket_branches SET pr_number = ?, pr_status = ?, pr_url = ?, "
            "last_synced = ? "
            "WHERE project_id = ? AND branch_name = ?",
            (
                pr_number,
                pr_status,
                pr_url,
                datetime.now().isoformat(),
                project_id,
                head_ref,
            ),
        )
        if cur.rowcount > 0:
            updated += cur.rowcount
            continue

        # Try auto-linking if the branch matches a ticket ID
        matched_tid = _match_branch_to_ticket(head_ref, ticket_ids)
        if matched_tid:
            conn.execute(
                "INSERT OR IGNORE INTO ticket_branches "
                "(ticket_id, project_id, branch_name, remote, auto_linked, "
                "pr_number, pr_status, pr_url, last_synced) "
                "VALUES (?, ?, ?, 'origin', 1, ?, ?, ?, ?)",
                (
                    matched_tid,
                    project_id,
                    head_ref,
                    pr_number,
                    pr_status,
                    pr_url,
                    datetime.now().isoformat(),
                ),
            )
            updated += 1

    return {"updated": updated}


# ---------------------------------------------------------------------------
# Lane B helpers — activity feed and children rollup.
# These are pure DB reads; no mutations, no commits.
# ---------------------------------------------------------------------------


def get_ticket_activity(
    conn: sqlite3.Connection,
    project_id: str,
    ticket_id: str,
    limit: int = 50,
    before: str | None = None,
) -> list[dict]:
    """Return activity_events for a ticket, newest-first, with optional cursor.

    Uses the (project_id, subject_type, subject_id, occurred_at DESC) index.
    Pagination cursor `before` is an ISO-8601 timestamp (exclusive upper bound).

    Returns a list of event dicts:
        {id, occurred_at, actor_type, actor_id, event_kind, payload, run_id}
    where run_id is extracted from payload['run_id'] when present.
    """
    limit = max(1, min(limit, 500))

    # Resolve canonical ID (subject_id stored case-sensitively by emit_event).
    row = conn.execute(
        "SELECT id FROM tickets WHERE UPPER(id) = UPPER(?) AND project_id = ?",
        (ticket_id, project_id),
    ).fetchone()
    tid = row["id"] if row else ticket_id

    if before:
        rows = conn.execute(
            "SELECT id, actor_type, actor_id, event_kind, payload_json, "
            "       occurred_at, discarded_run_id "
            "FROM activity_events "
            "WHERE project_id = ? AND subject_type = 'ticket' AND subject_id = ? "
            "  AND occurred_at < ? "
            "ORDER BY occurred_at DESC, id DESC LIMIT ?",
            (project_id, tid, before, limit),
        ).fetchall()
    else:
        rows = conn.execute(
            "SELECT id, actor_type, actor_id, event_kind, payload_json, "
            "       occurred_at, discarded_run_id "
            "FROM activity_events "
            "WHERE project_id = ? AND subject_type = 'ticket' AND subject_id = ? "
            "ORDER BY occurred_at DESC, id DESC LIMIT ?",
            (project_id, tid, limit),
        ).fetchall()

    # Resolve agent display names in one batch — for actor_type='agent', actor_id
    # is a run_id. Kitchen runs (integer ids) carry workflow_name in metadata_json;
    # workflow_bounce runs (uuid string ids) link to workflows.name.
    agent_run_ids: set[str] = {
        r["actor_id"] for r in rows if r["actor_type"] == "agent" and r["actor_id"]
    }
    actor_name_by_run: dict[str, str] = {}
    if agent_run_ids:
        # Try kitchen runs (numeric ids)
        numeric_ids = [rid for rid in agent_run_ids if rid.isdigit()]
        if numeric_ids:
            placeholders = ",".join("?" * len(numeric_ids))
            kitchen_rows = conn.execute(
                f"SELECT id, metadata_json FROM runs WHERE id IN ({placeholders})",
                numeric_ids,
            ).fetchall()
            for kr in kitchen_rows:
                try:
                    meta = json.loads(kr["metadata_json"] or "{}")
                except (json.JSONDecodeError, TypeError):
                    meta = {}
                name = meta.get("workflow_name") or meta.get("agent_name")
                if name:
                    actor_name_by_run[str(kr["id"])] = name
        # Try workflow_bounce runs (uuid ids)
        uuid_ids = [rid for rid in agent_run_ids if not rid.isdigit()]
        if uuid_ids:
            placeholders = ",".join("?" * len(uuid_ids))
            try:
                wf_rows = conn.execute(
                    f"SELECT wr.id AS id, w.name AS name "
                    f"FROM workflow_runs wr LEFT JOIN workflows w ON w.id = wr.workflow_id "
                    f"WHERE wr.id IN ({placeholders})",
                    uuid_ids,
                ).fetchall()
                for wr in wf_rows:
                    if wr["name"]:
                        actor_name_by_run[wr["id"]] = wr["name"]
            except sqlite3.OperationalError:
                # workflow_runs table may not exist on minimal schemas
                pass

    events = []
    for r in rows:
        try:
            payload = json.loads(r["payload_json"]) if r["payload_json"] else {}
        except (json.JSONDecodeError, TypeError):
            payload = {}
        actor_name = None
        if r["actor_type"] == "agent" and r["actor_id"]:
            actor_name = actor_name_by_run.get(r["actor_id"])
        events.append(
            {
                "id": r["id"],
                "occurred_at": r["occurred_at"],
                "actor_type": r["actor_type"],
                "actor_id": r["actor_id"],
                "actor_name": actor_name,
                "event_kind": r["event_kind"],
                "payload": payload,
                "run_id": payload.get("run_id"),
                "discarded_run_id": r["discarded_run_id"],
            }
        )
    return events


def get_children_summary(
    conn: sqlite3.Connection,
    project_id: str,
    parent_id: str,
) -> dict:
    """Return a rollup of children for a container ticket.

    Returns:
        {
            total: int,
            done: int,                       # section == 'Done'
            count_by_section: {section: n},
            count_by_status: {status: n},
        }
    """
    rows = conn.execute(
        "SELECT section, status FROM tickets "
        "WHERE parent = ? AND project_id = ? AND archived = 0",
        (parent_id, project_id),
    ).fetchall()

    count_by_section: dict[str, int] = {}
    count_by_status: dict[str, int] = {}
    done = 0
    for r in rows:
        count_by_section[r["section"]] = count_by_section.get(r["section"], 0) + 1
        count_by_status[r["status"]] = count_by_status.get(r["status"], 0) + 1
        if r["section"] == "Done":
            done += 1

    return {
        "total": len(rows),
        "done": done,
        "count_by_section": count_by_section,
        "count_by_status": count_by_status,
    }


# --- Bookmarks + Recents --------------------------------------------------
#
# Per-project, per-ticket UI state. Not event-emitting — these are personal
# navigation aids, not ticket state changes.

RECENTS_CAP = 20


def toggle_bookmark(conn: sqlite3.Connection, project_id: str, ticket_id: str) -> bool:
    """Toggle bookmark for a ticket. Returns the new bookmark state (True=bookmarked).

    Removing a bookmark also touches recents — unbookmarking counts as a
    'just viewed' signal so the ticket re-appears under Recents instead of
    vanishing entirely from the nav.
    """
    ticket = _find_ticket(conn, project_id, ticket_id)
    tid = ticket["id"]
    row = conn.execute(
        "SELECT 1 FROM ticket_bookmarks WHERE project_id = ? AND ticket_id = ?",
        (project_id, tid),
    ).fetchone()
    if row:
        conn.execute(
            "DELETE FROM ticket_bookmarks WHERE project_id = ? AND ticket_id = ?",
            (project_id, tid),
        )
        # Treat unbookmarking as a fresh view so the ticket lands in Recents.
        _touch_recent_row(conn, project_id, tid)
        conn.commit()
        return False
    conn.execute(
        "INSERT INTO ticket_bookmarks (project_id, ticket_id, created_at) VALUES (?, ?, ?)",
        (project_id, tid, utcnow_iso()),
    )
    conn.commit()
    return True


def _touch_recent_row(
    conn: sqlite3.Connection, project_id: str, ticket_id: str
) -> None:
    """Inner upsert + trim — no separate commit, callers commit as part of
    their own transaction."""
    conn.execute(
        """
        INSERT INTO ticket_recents (project_id, ticket_id, last_seen_at)
        VALUES (?, ?, ?)
        ON CONFLICT(project_id, ticket_id) DO UPDATE SET last_seen_at = excluded.last_seen_at
        """,
        (project_id, ticket_id, utcnow_iso()),
    )
    conn.execute(
        """
        DELETE FROM ticket_recents
        WHERE project_id = ?
          AND ticket_id NOT IN (
              SELECT ticket_id FROM ticket_recents
              WHERE project_id = ?
              ORDER BY last_seen_at DESC
              LIMIT ?
          )
        """,
        (project_id, project_id, RECENTS_CAP),
    )


def list_bookmarks(conn: sqlite3.Connection, project_id: str) -> list[dict]:
    """List bookmarked tickets for a project. Filters out tickets that no longer exist."""
    rows = conn.execute(
        """
        SELECT t.id AS id, t.title AS title, t.section AS section,
               t.status AS status, b.created_at AS created_at
        FROM ticket_bookmarks b
        INNER JOIN tickets t
          ON t.project_id = b.project_id AND t.id = b.ticket_id
        WHERE b.project_id = ?
        ORDER BY b.created_at DESC
        """,
        (project_id,),
    ).fetchall()
    return [dict(r) for r in rows]


def is_bookmarked(conn: sqlite3.Connection, project_id: str, ticket_id: str) -> bool:
    row = conn.execute(
        "SELECT 1 FROM ticket_bookmarks WHERE project_id = ? AND ticket_id = ?",
        (project_id, ticket_id),
    ).fetchone()
    return bool(row)


def touch_recent(conn: sqlite3.Connection, project_id: str, ticket_id: str) -> None:
    """Record that the user opened this ticket. Trims oldest beyond RECENTS_CAP."""
    ticket = _find_ticket(conn, project_id, ticket_id)
    _touch_recent_row(conn, project_id, ticket["id"])
    conn.commit()


def list_recents(
    conn: sqlite3.Connection, project_id: str, limit: int = RECENTS_CAP
) -> list[dict]:
    """List recently-opened tickets, newest first. Excludes tickets that
    are currently bookmarked — a ticket is in exactly one of Bookmarks or
    Recents at any time."""
    rows = conn.execute(
        """
        SELECT t.id AS id, t.title AS title, t.section AS section,
               t.status AS status, r.last_seen_at AS last_seen_at
        FROM ticket_recents r
        INNER JOIN tickets t
          ON t.project_id = r.project_id AND t.id = r.ticket_id
        LEFT JOIN ticket_bookmarks b
          ON b.project_id = r.project_id AND b.ticket_id = r.ticket_id
        WHERE r.project_id = ? AND b.ticket_id IS NULL
        ORDER BY r.last_seen_at DESC
        LIMIT ?
        """,
        (project_id, limit),
    ).fetchall()
    return [dict(r) for r in rows]
